project_id = "kmbhlrcrplvfmicoxmul"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.notify-enquiry]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.generate-description]
verify_jwt = false